# Dockerfile References: https://docs.docker.com/engine/reference/builder/
# pulled from https://www.callicoder.com/deploy-containerized-go-app-kubernetes/

# Start from the latest golang base image
FROM golang:1.13 as builder

# Add Maintainer Info
LABEL maintainer="Bryan Sandoval <bmsandoval@gmail.com>"

WORKDIR /app

RUN go get github.com/githubnemo/CompileDaemon

## This container exposes port 8080 to the outside world
EXPOSE 8080

#ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -v -mod vendor -o main ./" -command="./main"
